CREATE TABLE spittle (
  id INT NOT NULL AUTO_INCREMENT,
  message VARCHAR(140) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  longitude DOUBLE,
  latitude DOUBLE,
  PRIMARY KEY (id)
);

CREATE TABLE spitter (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) UNIQUE NOT NULL,
  password VARCHAR(20) NOT NULL,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);